### ISSUE TITLE
TestTriangle2D3PointLocalCoordinates fails in Travis

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1548]
The test fails in Travis, see #1546 
~~~
    TestTriangle2D3PointLocalCoordinates Failed with message: 
        Error: Check failed becuase baricentre_local_coords(0) = 9.33784e-322 is not near to 1.0/3.0 = 0.333333 within the tolerance 1e-06
in kratos/tests/geometries/test_triangle_2d_3.cpp:216:virtual void Testing::TestTriangle2D3PointLocalCoordinates::TestFunction()
~~~
@rubenzorrilla I saw that you made this test, can you please have a look?

It does not fail on my machine, so maybe it is related to some tolerance

**Comment by pooyan-dadvand** [comment]
I think that the `GenerateIrregularTriangle2D3` is calling a wrong constructor. @rubenzorrilla why you are not using geometry of point for testing? Nodes are more error prone to be constructed without a ModelPart.

**Comment by rubenzorrilla** [comment]
If I'm not wrong, @roigcarlo implemented that function (I just used it to generate the testing triangle). Probably he can put some light on that. In any case, I'll check it.

**Comment by roigcarlo** [comment]
Yep I did that one some time ago while adding the quality function tests so we could also test the geometry utils functions.

I spoke with @rubenzorrilla and seems that the problem is that geometry utils functions make use of:
```C++
Element::GeometryType& geom
```
Which is defined as `Geometry<Node<3>>` by `element.h`.
So either we let that specific tests with Nodes or we change the geometryUtils class so it accepts any instance of geometry.

There will be other tests with the same problem (the ones that calculate the gauss points)

**Comment by rubenzorrilla** [comment]
At a first glace, I noted that I was creating the testing point which point local coordinates are to be computed as an array_1d instead of a Point. I am not completely sure if this might be the origin of the problem (just in case and to be consistent I'm changing that in PD #1561).

Related to what @roigcarlo is pointing out, I did try to change all the Node<3> by Points, except the ones that use the GeometryUtils, and a large number of tests do not return the expected result... Maybe there are more insights that we are not taking into account.

**Comment by pooyan-dadvand** [comment]
So you may have to generate triangle methods one for `Node` calling the constructor with id and another for `Point` 

I agree with changing the geometry tests to point when is possible because it reduces the complexities of creating a new node.

**Comment by rubenzorrilla** [comment]
Solved in #1561.

**Comment by philbucher** [comment]
Unfortunately it still fails in Travis
~~~
TestTriangle2D3PointLocalCoordinates Failed with message: 
        Error: Check failed because baricentre_local_coords(0) = 1.18576e-322 is not near to 1.0/3.0 = 0.333333 within the tolerance 1e-06
in kratos/tests/geometries/test_triangle_2d_3.cpp:236:virtual void Testing::TestTriangle2D3PointLocalCoordinates::TestFunction()
~~~

**Comment by pooyan-dadvand** [comment]
@rubenzorrilla and @roigcarlo would yo please take a look at it?

**Comment by roigcarlo** [comment]
Ok let me take a look

**Comment by roigcarlo** [comment]
Still testing this, it fails in travis but I am not able to reproduce it in my computer...

**Comment by rubenzorrilla** [comment]
Me neither...

**Comment by philbucher** [comment]
Me neither

**Comment by pooyan-dadvand** [comment]
would you please compile it in full debug and pass it to the valgrind? (only this test)

**Comment by roigcarlo** [comment]
Already done, output is clean just a warning about node DOF. 

```
Syscall param sched_setaffinity(mask) points to unaddressable byte(s)
 59 ==20654==    at 0x5147819: syscall (in /usr/lib/libc-2.26.so)
 60 ==20654==    by 0xDE70F05: ??? (in /usr/lib/libomp.so)
 61 ==20654==    by 0xDE3936A: ??? (in /usr/lib/libomp.so)
 62 ==20654==    by 0xDE275C9: ??? (in /usr/lib/libomp.so)
 63 ==20654==    by 0xDE2784C: ??? (in /usr/lib/libomp.so)
 64 ==20654==    by 0xDE7AF29: omp_init_lock (in /usr/lib/libomp.so)
 65 ==20654==    by 0xA00AF36: Kratos::Node<3ul, Kratos::Dof<double> >::Node() (node.h:146)
 66 ==20654==    by 0xC9D3832: Kratos::KratosApplication::RegisterVariables() (variables.cpp:1007)
 67 ==20654==    by 0xCB3DA15: Kratos::Kernel::Kernel() (kernel.cpp:28)
 68 ==20654==    by 0xA691DF2: boost::python::objects::pointer_holder<boost::shared_ptr<Kratos::Kernel>, Kratos::Kernel>::pointer_holder(_object*) (pointer_holder.hpp:195)
 69 ==20654==    by 0xA691D0A: boost::python::objects::make_holder<0>::apply<boost::python::objects::pointer_holder<boost::shared_ptr<Kratos::Kernel>, Kratos::Kernel>, boost::mpl::vector0<mpl    _::na> >::execute(_object*) (make_holder.hpp:94)
 70 ==20654==    by 0xA08E140: _object* boost::python::detail::invoke<int, void (*)(_object*), boost::python::arg_from_python<_object*> >(boost::python::detail::invoke_tag_<true, false>, int     const&, void (*&)(_object*), boost::python::arg_from_python<_object*>&) (invoke.hpp:79)
 71 ==20654==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

I found I way to use the docker image that travis use locally. I am gonna try to build that in my computer an repeat the exact same process travis is executing to debug it there.

**Comment by pooyan-dadvand** [comment]
Thanks @roigcarlo !

**Comment by roigcarlo** [comment]
No errors for that test, but I got one in:

```
FAIL: test_SmallDisplacementBbarElement_2D_quadrilateral (test_patch_test_small_strain_bbar.TestPatchTestSmallStrainBbar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_small_strain_bbar.py", line 257, in test_SmallDisplacementBbarElement_2D_quadrilateral
    self._check_results(mp,A,b)
  File "/home/travis/KratosMultiphysics/Kratos/applications/StructuralMechanicsApplication/tests/test_patch_test_small_strain_bbar.py", line 141, in _check_results
    self.assertAlmostEqual(d[2], u[2])
AssertionError: 0.0 != 5.463809250812225e+68 within 7 places
```

I keep investigating...

**Comment by philbucher** [comment]
@roigcarlo sorry for this, you can deactivate this test if you want to merge #1546 
@loumalouomega @marandra can you please have a look at it?

Shows once more that the tests are needed for merging :D

**Comment by philbucher** [comment]
fixed in #1546
