### ISSUE TITLE
Compiler Error under linux with Intel compiler

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1971]
Hi @roigcarlo 
I am trying to compile Kratos with the Intel compiler version 16 but unfortunately I get an error
Before pybind it was compileing with the same configuration
This error shows up several times
~~~
In file included from /home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/cast.h(15),
                 from /home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/attr.h(13),
                 from /home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/pybind11.h(43),
                 from /home/hpc/pr94va/ga59vax3/software/Kratos/applications/ExternalSolversApplication/custom_python/externalsolvers_python_application.cpp(13):
/home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/detail/descr.h(59): error: expression must have a constant value
      static constexpr auto digits = descr<sizeof...(Digits)>(('0' + Digits)...);
~~~

As usual thx for your help

**Comment by philbucher** [comment]
Seems like this is a known pybind issue, see [here](https://github.com/pybind/pybind11/issues/1121)
I will try with a newer version of the compiler and report the results

**Comment by roigcarlo** [comment]
:+1: I read that this is fixed in pybind master, if it is the case we may take that change and apply it in our version

**Comment by philbucher** [comment]
I just checked, this fix is already in Kratos, it is still not working.
At the end of this issue they say that they are dropping support for intel compiler version <=2016 (I used 2016)
Now I am trying with 2017

**Comment by philbucher** [comment]
with 2017 I get the following error, now it seems related to Kratos:
~~~
/home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/pybind11.h(1219): error: no instance of overloaded function "pybind11::method_adaptor" matches the argument list
            argument types are: (void (Kratos::Point &, double))
          return def_property(name, fget, cpp_function(method_adaptor<type>(fset)), extra...);
                                                       ^
/home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/pybind11.h(1006): note: this candidate was rejected because at least one template argument could not be deduced
  auto method_adaptor(Return (Class::*pmf)(Args...) const) -> Return (Derived::*)(Args...) const {
       ^
/home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/pybind11.h(999): note: this candidate was rejected because at least one template argument could not be deduced
  auto method_adaptor(Return (Class::*pmf)(Args...)) -> Return (Derived::*)(Args...) {
       ^
/home/hpc/pr94va/ga59vax3/software/Kratos/external_libraries/pybind11/pybind11.h(996): note: this candidate was rejected because at least one template argument could not be deduced
  auto method_adaptor(F &&f) -> decltype(std::forward<F>(f)) { return std::forward<F>(f); }
       ^
          detected during instantiation of "pybind11::class_<type_, options...> &pybind11::class_<type_, options...>::def_property(const char *, const Getter &, const Setter &, const Extra &...) [with type_=Kratos::Point, options=<Kratos::Point::Pointer, Kratos::array_1d<double, 3UL>>, Getter=double (Kratos::Point &), Setter=void (Kratos::Point &, double), Extra=<>]" at line 72 of "/home/hpc/pr94va/ga59vax3/software/Kratos/kratos/python/add_points_to_python.cpp"
~~~

**Comment by philbucher** [comment]
@roigcarlo unfortunately the errors did not disappear, I tried with different versions of the 2017 compiler

The errors are coming from Kratos though, so I think it can be fixed.
I attached the log file of the compilation, 147 errors (search for "error"), there are also a lot of warnings, see #1973 
I think all the errors have the same origin
[configure_stderr.log](https://github.com/KratosMultiphysics/Kratos/files/1954750/configure_stderr.log)

**Comment by roigcarlo** [comment]
Ok I'll take a look. Mini-holiday in Spain, so fix wont be until Wednesday

**Comment by philbucher** [comment]
same here
Thx a lot!

**Comment by philbucher** [comment]
The cluster had a software update in the meantime, unfortunately the error hasn't disappeared :/
Seems to be always the same problem, here is the latest log (search for "error")
[configure_stdout.log](https://github.com/KratosMultiphysics/Kratos/files/1966039/configure_stdout.log)
[configure_stderr.log](https://github.com/KratosMultiphysics/Kratos/files/1966040/configure_stderr.log)

**Comment by roigcarlo** [comment]
@philbucher I will have a machine with intel ready by noon, in the meantime, could you try to compile with -std=c++14 and check if the same errors disappear? @RiccardoRossi and I want to test something.

**Comment by philbucher** [comment]
Thanks @roigcarlo 

I recompiled with c++14 but it seems like I get the same error
I hope I correctly set the flag for enabling c++14, according to the log it should be

[configure_stderr.log](https://github.com/KratosMultiphysics/Kratos/files/1966432/configure_stderr.log)
[configure_stdout.log](https://github.com/KratosMultiphysics/Kratos/files/1966433/configure_stdout.log)

**Comment by philbucher** [comment]
same error with c++17

**Comment by roigcarlo** [comment]
I think I located the problem, but still not sure why its happening only with Intel compiler.
Seems that some entry points that used an auxiliary function need the & before its name, but others do not and I still don't know why this is happening.

At list the & trick seems to solve the problem

**Comment by vineetmoraybfab** [comment]
> At list the & trick seems to solve the problem

Can you let us know how?
I am also having the same issue with Intel compilers(2017).
Thanks.

**Comment by philbucher** [comment]
the corrections required to make it work are implemented in #2000 

the branch is called `pybind/fixing-pybind-intel-interface`

This one compiles (I am using it) but there might be some problems with openMP, see #2000

**Comment by philbucher** [comment]
This is fixed, Kratos requires the Intel Compiler 2018 to compile (I added a proper error message in #2404 )
