### ISSUE TITLE
[StructuralMechanicsApplication] kratos_utilities has no attribute CheckIfApplicationsAvailable 

### ISSUE THREAD

**Issue by philipkalkbrenner** [KratosMultiphysics/Kratos#4296]
My jobs dont run since the structural_mechanics_solver.py calls the attribute "CheckIfApplicationsAvailable" from kratos_utilities, but in the kratos_utilities it is still "IsApplicationAvailable". 
Is it an error coming from my machine or from the master?

**Comment by philbucher** [comment]
delete the folder `KratosMultiphysics` and recompile should solve the problem

btw you should delete this folder and the `libs` folder every time you compile to make sure there are no leftovers, which could cause strange errors like the one you are reporting

@roigcarlo maybe it is time to find a permanent solution for this, many ppl seem to have problems

**Comment by roigcarlo** [comment]
Hi @philbucher , nothing but removing the folder ill work. I canforce the folder to be deleted every time kratos is installed but I still don't have green light to do it. I will airse the topic tomorrow as we have a meeting...

**Comment by philbucher** [comment]
> Hi @philbucher , nothing but removing the folder ill work.

I know :)

> I canforce the folder to be deleted every time kratos is installed but I still don't have green light to do it. I will airse the topic tomorrow as we have a meeting...

:+1:
