### ISSUE TITLE
How to add CalculateOnIntegrationPoints for bool variables to Python?

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#8163]
**Description**
Apparently CalculateOnIntegrationPoints for boolean variables is not exported to python
```
TypeError: CalculateOnIntegrationPoints(): incompatible function arguments. The following argument types are supported:
    1. (self: Kratos.Element, arg0: Kratos.IntegerVariable, arg1: Kratos::ProcessInfo) -> list
    2. (self: Kratos.Element, arg0: Kratos.DoubleVariable, arg1: Kratos::ProcessInfo) -> list
    3. (self: Kratos.Element, arg0: Kratos.Array1DVariable3, arg1: Kratos::ProcessInfo) -> list
    4. (self: Kratos.Element, arg0: Kratos.VectorVariable, arg1: Kratos::ProcessInfo) -> list
    5. (self: Kratos.Element, arg0: Kratos.MatrixVariable, arg1: Kratos::ProcessInfo) -> list

Invoked with: <Kratos.Element object at 0x7fc25ec657f0>, <Kratos.BoolVariable object at 0x7fc25b35eb70>, <Kratos.ProcessInfo object at 0x7fc25ec4e570>
```

I tried adding
`.def("CalculateOnIntegrationPoints", CalculateOnIntegrationPoints<Element, bool>)`
to line 465ish of `.../kratos/python/add_mesh_to_python.cpp`, but it seems not to be enough:
`SystemError: <built-in method CalculateOnIntegrationPoints of PyCapsule object at 0x7f65df530060> returned a result with an error set`

Is it missing something else?

**Scope**
- Python

**Comment by loumalouomega** [comment]
See  #8164

**Comment by loumalouomega** [comment]
Should work now

**Comment by marandra** [comment]
Hi @loumalouomega, thanks for looking into it.

I've been testing it after #8164, and I'm still getting the original error. When trying to retrieve a boolean variable with CalculateOnIntegrationPoints(...) it stops with these messages:
```
... (normal output) ...
ResidualBasedNewtonRaphsonStrategy: Convergence achieved after 2 / 10 iterations
SystemError: Objects/listobject.c:317: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Compartido/Cases/TEMP_HOM/sampling/case_005/MainKratos.py", line 12, in <module>
    simulation.Run()
  File "/home/marcelo/Projects/Kratos/bin/current/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/marcelo/Projects/Kratos/bin/current/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/marcelo/Projects/Kratos/bin/current/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/marcelo/Projects/Kratos/bin/current/KratosMultiphysics/MultiscaleROMApplication/kratos_process_is_elastic.py", line 70, in ExecuteFinalizeSolutionStep
    self.is_elastic = self.check_all_points_elastic()
  File "/home/marcelo/Projects/Kratos/bin/current/KratosMultiphysics/MultiscaleROMApplication/kratos_process_is_elastic.py", line 42, in check_all_points_elastic
    flag_bool = elem.CalculateOnIntegrationPoints(
SystemError: <built-in method CalculateOnIntegrationPoints of PyCapsule object at 0x7f18f0540c30> returned a result with an error set
BuilderAndSolver: Clear Function called
BuilderAndSolver: Clear Function called
```

An equivalent code, but using a double variable, passes normally.

**Comment by loumalouomega** [comment]
OK, apparently the pybind11 lists cannot store booleans, so I have done a refactor for the booleans parsing integers. Now it works

**Comment by loumalouomega** [comment]
See #8179
