### ISSUE TITLE
Sign criterion for MOMENT components in the Linear Beam Element

### ISSUE THREAD

**Issue by clazaro** [KratosMultiphysics/Kratos#9181]
Hi KratosMultiphysics team! As I told @RiccardoRossi , we are starting to develop a project at the UPV with @BenjaPH which will use the StructuralMechanicsApplication. Among other things we will need to modify the Beam element to include prescribed strains/curvatures to model temperature changes and gradients. Before starting that, we are testing the element to become familiar with the whole setup. We found the following:

**Description**
I tested a straight cantilever with 10 elements using the CrLinearBeamElement3D2N using Kratos 8.1 (the one you import with GiD). Beam local axes are coincident with the global ones (LOCAL_AXIS_2 = [0., 1., 0.] and the element connectivity increases in the same way as the node numbering: element 1 has nodes 1 and 2 and so on; node 1 is at [0., 0., 0.] and node 11 is at [10., 0., 0.] - note that this ordering is different as the one created by GiD by default). I apply a point moment at the free end with value [1000., 1000., 1000.]. The solution is OK in terms of displacements and rotations. However, I retrieve the internal moments at the integration points (which should be [1000., 1000., 1000.] using a "standard" criterion for signs) and I get that the sign of the third component of the moment (just this one) is negative. Which is the criterion used for the internal moments?

I am attaching the example in a compressed zip file; you will see that the custom StructuralMechanicsAnalysis class modifies the point moment and allows for printing results.

**Scope**
Structural Mechanics Application

[Simple_Beam_Isssue.zip](https://github.com/KratosMultiphysics/Kratos/files/7285058/Simple_Beam_Isssue.zip)

**Comment by rubenzorrilla** [comment]
Pinging @KratosMultiphysics/structural-mechanics and @KlausBSautter, who will most probably know about this.

**Comment by KlausBSautter** [comment]
I'll check it

**Comment by KlausBSautter** [comment]
@clazaro thanks for the hint. Apparently, there was a sign error. Should be fixed with #9183.

**Comment by clazaro** [comment]
Many thanks @KlausBSautter!

**Comment by clazaro** [comment]
Hi @KlausBSautter, the linear beam element is still wrong... See lines 255 to 257 of `cr_beam_element_linear_3D2N.cpp`
~~~
    if (rVariable == MOMENT) {
        rOutput[0][0] = -1.0 * stress[3] * 0.75 + stress[9] * 0.25;
        rOutput[1][0] = -1.0 * stress[3] * 0.50 + stress[9] * 0.50;
        rOutput[2][0] = -1.0 * stress[3] * 0.25 + stress[9] * 0.75;

        rOutput[0][1] = -1.0 * stress[4] * 0.75 + stress[10] * 0.25;
        rOutput[1][1] = -1.0 * stress[4] * 0.50 + stress[10] * 0.50;
        rOutput[2][1] = -1.0 * stress[4] * 0.25 + stress[10] * 0.75;

        rOutput[0][2] = 1.0 * stress[5] * 0.75 - stress[11] * 0.25;
        rOutput[1][2] = 1.0 * stress[5] * 0.50 - stress[11] * 0.50;
        rOutput[2][2] = 1.0 * stress[5] * 0.25 - stress[11] * 0.75;
    }
~~~

**Comment by KlausBSautter** [comment]
... we only fixed the non-linear beam, nice ....
